using Milvus.Client.V2.Utils;
namespace Milvus.Client.V2.Types;

/// <summary>
/// Defines the schema of a single field in a <see cref="CollectionSchema" />.
/// </summary>
public sealed class FieldSchema
{
    /// <summary>
    /// Creates a new field schema.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="dataType">The data type of the field.</param>
    /// <param name="isPrimaryKey">Whether the field is the primary key of the collection.</param>
    /// <param name="autoId">Whether primary key values are automatically generated by Milvus.</param>
    /// <param name="isPartitionKey">Whether the field is a partition key.</param>
    /// <param name="description">An optional description for the field.</param>
    public FieldSchema(
        string name,
        DataType dataType,
        bool isPrimaryKey = false,
        bool autoId = false,
        bool isPartitionKey = false,
        string description = "")
    {
        Verify.NotNullOrWhiteSpace(name);

        Name = name;
        DataType = dataType;
        IsPrimaryKey = isPrimaryKey;
        AutoId = autoId;
        IsPartitionKey = isPartitionKey;
        Description = description;
    }

    /// <summary>
    /// Creates a new <see cref="DataType.VarChar" /> field schema.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="maxLength">The maximum length of the varchar field. Must be greater than zero.</param>
    /// <param name="isPrimaryKey">Whether the field is the primary key of the collection.</param>
    /// <param name="autoId">Whether primary key values are automatically generated by Milvus.</param>
    /// <param name="isPartitionKey">Whether the field is a partition key.</param>
    /// <param name="description">An optional description for the field.</param>
    /// <param name="nullable">Whether the field is nullable.</param>
    /// <param name="defaultValue">The default value for the field.</param>
    /// <param name="enableAnalyzer">Whether the analyzer is enabled for this field (BM25 full-text search).</param>
    /// <param name="analyzerParams">The analyzer parameters, e.g. <c>new Dictionary&lt;string, object&gt; { ["type"] = "english" }</c>.</param>
    public static FieldSchema CreateVarchar(
        string name,
        int maxLength,
        bool isPrimaryKey = false,
        bool autoId = false,
        bool isPartitionKey = false,
        string description = "",
        bool nullable = false,
        string? defaultValue = null,
        bool enableAnalyzer = false,
        IReadOnlyDictionary<string, object>? analyzerParams = null)
        => new(name, DataType.VarChar, isPrimaryKey, autoId, isPartitionKey, description)
        {
            MaxLength = maxLength,
            Nullable = nullable,
            DefaultValue = defaultValue,
            EnableAnalyzer = enableAnalyzer,
            AnalyzerParams = analyzerParams
        };

    /// <summary>
    /// Creates a new <see cref="DataType.FloatVector" /> field schema.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="dimension">The dimensionality of the vector. Must be greater than zero.</param>
    /// <param name="description">An optional description for the field.</param>
    public static FieldSchema CreateFloatVector(string name, int dimension, string description = "")
        => new(name, DataType.FloatVector, description: description)
        {
            Dimension = dimension
        };

    /// <summary>
    /// Creates a new <see cref="DataType.SparseFloatVector" /> field schema.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="description">An optional description for the field.</param>
    public static FieldSchema CreateSparseFloatVector(string name, string description = "")
        => new(name, DataType.SparseFloatVector, description: description);

    /// <summary>
    /// The field name.
    /// </summary>
    public string Name { get; }

    /// <summary>
    /// The data type of the field.
    /// </summary>
    public DataType DataType { get; }

    /// <summary>
    /// Whether the field is the primary key of the collection.
    /// </summary>
    public bool IsPrimaryKey { get; }

    /// <summary>
    /// Whether primary key values are automatically generated by Milvus.
    /// </summary>
    public bool AutoId { get; }

    /// <summary>
    /// Whether the field is a partition key.
    /// </summary>
    public bool IsPartitionKey { get; }

    /// <summary>
    /// An optional description for the field.
    /// </summary>
    public string Description { get; }

    /// <summary>
    /// The maximum length of a <see cref="DataType.VarChar" /> field.
    /// </summary>
    public int? MaxLength { get; set; }

    /// <summary>
    /// The dimensionality of a vector field.
    /// </summary>
    public int? Dimension { get; set; }

    /// <summary>
    /// The maximum capacity of an array field.
    /// </summary>
    public int? MaxCapacity { get; set; }

    /// <summary>
    /// The element data type of an array field.
    /// </summary>
    public DataType? ElementDataType { get; set; }

    /// <summary>
    /// Whether the field is nullable.
    /// </summary>
    public bool Nullable { get; set; }

    /// <summary>
    /// The default value for the field.
    /// </summary>
    public object? DefaultValue { get; set; }

    /// <summary>
    /// Whether the analyzer is enabled for this field (BM25 full-text search input fields).
    /// </summary>
    public bool EnableAnalyzer { get; set; }

    /// <summary>
    /// The analyzer parameters, e.g. <c>new Dictionary&lt;string, object&gt; { ["type"] = "english" }</c>.
    /// </summary>
    public IReadOnlyDictionary<string, object>? AnalyzerParams { get; set; }

    /// <summary>
    /// Whether this field is the output of a function (e.g. a BM25 sparse vector field).
    /// </summary>
    public bool IsFunctionOutput { get; internal set; }
}
