using System.Diagnostics;
using System.Globalization;
using System.Text.Json;

namespace Milvus.Client;

/// <summary>
/// The logical definition of a field within a <see cref="CollectionSchema" />.
/// </summary>
[DebuggerDisplay("{DebuggerDisplay,nq}")]
public sealed class FieldSchema
{
    /// <summary>
    /// Create a field schema.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="dataType">The data type stored in the field.</param>
    /// <param name="isPrimaryKey">Whether the field is a primary key.</param>
    /// <param name="autoId">Whether the field's values are automatically generated by Milvus.</param>
    /// <param name="isPartitionKey">
    /// Whether the field functions as the partition key for the collection. Available since Milvus v2.2.9.
    /// </param>
    /// <param name="description">An optional description for the field.</param>
    /// <param name="nullable">Whether the field can contain null values. Available since Milvus v2.5.</param>
    /// <param name="defaultValue">
    /// The default value for the field. Available since Milvus v2.5.
    /// Only supported for scalar fields. Not supported for arrays, JSON, or vector fields.
    /// </param>
    public static FieldSchema Create(
        string name,
        MilvusDataType dataType,
        bool isPrimaryKey = false,
        bool autoId = false,
        bool isPartitionKey = false,
        string description = "",
        bool nullable = false,
        object? defaultValue = null)
        => new(name, dataType, isPrimaryKey, autoId, isPartitionKey, description, nullable, defaultValue);

    /// <summary>
    /// Create a field schema.
    /// </summary>
    /// <typeparam name="TData">Determines the data type stored in the field based.</typeparam>
    /// <param name="name">The field name.</param>
    /// <param name="isPrimaryKey">Whether the field is a primary key.</param>
    /// <param name="autoId">Whether the field's values are automatically generated by Milvus.</param>
    /// <param name="isPartitionKey">
    /// Whether the field functions as the partition key for the collection. Available since Milvus v2.2.9.
    /// </param>
    /// <param name="description">An optional description for the field.</param>
    /// <param name="nullable">
    /// Whether the field can contain null values. Available since Milvus v2.5.
    /// <para>When null (default):</para>
    /// <list type="bullet">
    /// <item>Nullable value types (e.g., int?, bool?) → inferred as nullable=true</item>
    /// <item>Non-nullable value types (e.g., int, bool) → inferred as nullable=false</item>
    /// <item>Reference types (e.g., string) → inferred as nullable=false</item>
    /// </list>
    /// <para>When explicitly set:</para>
    /// <list type="bullet">
    /// <item>nullable=true on non-nullable value types → throws ArgumentException</item>
    /// <item>nullable=false on nullable value types → throws ArgumentException</item>
    /// <item>nullable=true on reference types or nullable value types → allowed</item>
    /// <item>nullable=false on reference types or non-nullable value types → allowed</item>
    /// </list>
    /// </param>
    /// <param name="defaultValue">
    /// The default value for the field. Available since Milvus v2.5.
    /// Only supported for scalar fields. Not supported for arrays, JSON, or vector fields.
    /// </param>
    public static FieldSchema Create<TData>(
        string name,
        bool isPrimaryKey = false,
        bool autoId = false,
        bool isPartitionKey = false,
        string description = "",
        bool? nullable = null,
        object? defaultValue = null)
    {
        Type? underlyingType = System.Nullable.GetUnderlyingType(typeof(TData));
        bool isNullableValueType = underlyingType is not null;
        bool shouldBeNullable = nullable ?? isNullableValueType;

        if (nullable == true && typeof(TData).IsValueType && !isNullableValueType)
        {
            throw new ArgumentException(
                $"Type {typeof(TData).Name} cannot be null. Use a nullable value type (e.g., {typeof(TData).Name}?) or remove the nullable parameter.",
                nameof(nullable));
        }

        if (nullable == false && isNullableValueType)
        {
            throw new ArgumentException(
                $"Type {typeof(TData).Name} is nullable but nullable=false was specified. Use the non-nullable type {underlyingType!.Name} instead.",
                nameof(nullable));
        }

        return new FieldSchema(name, FieldData.EnsureDataType<TData>(), isPrimaryKey, autoId,
            isPartitionKey, description, shouldBeNullable, defaultValue);
    }

    /// <summary>
    /// Create a field schema for a <c>varchar</c> field.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="maxLength">The maximum length of the <c>varchar</c> field. Must be greater than zero.</param>
    /// <param name="isPrimaryKey">Whether the field is a primary key.</param>
    /// <param name="autoId">Whether the field's values are automatically generated by Milvus.</param>
    /// <param name="isPartitionKey">
    /// Whether the field functions as the partition key for the collection. Available since Milvus v2.2.9.
    /// </param>
    /// <param name="description">An optional description for the field.</param>
    /// <param name="nullable">Whether the field can contain null values. Available since Milvus v2.5.</param>
    /// <param name="defaultValue">
    /// The default value for the field. Available since Milvus v2.5.
    /// </param>
    /// <param name="enableAnalyzer">
    /// Whether to enable the analyzer for this field. Required for BM25 full-text search input fields
    /// and for <paramref name="enableMatch" />-based <c>TEXT_MATCH</c> filtering.
    /// </param>
    /// <param name="analyzerParams">
    /// Optional analyzer parameters. For example: <c>new Dictionary&lt;string, object&gt; { ["type"] = "english" }</c>.
    /// </param>
    /// <param name="enableMatch">
    /// Whether to build an inverted index enabling <c>TEXT_MATCH</c> filter expressions against this
    /// field. Available since Milvus v2.5. Requires <paramref name="enableAnalyzer" /> to also be true.
    /// </param>
    public static FieldSchema CreateVarchar(
        string name,
        int maxLength,
        bool isPrimaryKey = false,
        bool autoId = false,
        bool isPartitionKey = false,
        string description = "",
        bool nullable = false,
        string? defaultValue = null,
        bool enableAnalyzer = false,
        IReadOnlyDictionary<string, object>? analyzerParams = null,
        bool enableMatch = false)
        => new(name, MilvusDataType.VarChar, isPrimaryKey, autoId, isPartitionKey, description, nullable, defaultValue)
        {
            MaxLength = maxLength,
            EnableAnalyzer = enableAnalyzer,
            AnalyzerParams = analyzerParams,
            EnableMatch = enableMatch
        };

    /// <summary>
    /// Create a field schema for a float vector field.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="dimension">The dimension of the vector. Must be greater than zero.</param>
    /// <param name="description">An optional description for the field.</param>
    public static FieldSchema CreateFloatVector(string name, int dimension, string description = "")
        => new(name, MilvusDataType.FloatVector, description: description) { Dimension = dimension };

    /// <summary>
    /// Create a field schema for a binary vector field.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="dimension">The dimension of the vector. Must be greater than zero.</param>
    /// <param name="description">An optional description for the field.</param>
    public static FieldSchema CreateBinaryVector(string name, int dimension, string description = "")
        => new(name, MilvusDataType.BinaryVector, description: description) { Dimension = dimension };

#if NET8_0_OR_GREATER
    /// <summary>
    /// Create a field schema for a float16 vector field.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="dimension">The dimension of the vector. Must be greater than zero.</param>
    /// <param name="description">An optional description for the field.</param>
    public static FieldSchema CreateFloat16Vector(string name, int dimension, string description = "")
        => new(name, MilvusDataType.Float16Vector, description: description) { Dimension = dimension };
#endif

    /// <summary>
    /// Create a field schema for a bfloat16 vector field. Available since Milvus v2.4.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="dimension">The dimension of the vector. Must be greater than zero.</param>
    /// <param name="description">An optional description for the field.</param>
    public static FieldSchema CreateBFloat16Vector(string name, int dimension, string description = "")
        => new(name, MilvusDataType.BFloat16Vector, description: description) { Dimension = dimension };

    /// <summary>
    /// Create a field schema for an int8 vector field. Available since Milvus v2.6.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="dimension">The dimension of the vector. Must be greater than zero.</param>
    /// <param name="description">An optional description for the field.</param>
    public static FieldSchema CreateInt8Vector(string name, int dimension, string description = "")
        => new(name, MilvusDataType.Int8Vector, description: description) { Dimension = dimension };

    /// <summary>
    /// Create a field schema for a JSON field.
    /// </summary>
    /// <param name="name">The field name.</param>
    public static FieldSchema CreateJson(string name)
        => new(name, MilvusDataType.Json);

    /// <summary>
    /// Create a field schema for a geometry field. Available since Milvus v2.6.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="description">An optional description for the field.</param>
    /// <param name="nullable">Whether the field accepts null values.</param>
    /// <remarks>
    /// Values are exchanged as WKT (well-known text), e.g. <c>POINT (30 10)</c>. Use
    /// <see cref="IndexType.RTree" /> to accelerate spatial predicates on this field.
    /// </remarks>
    public static FieldSchema CreateGeometry(string name, string description = "", bool nullable = false)
        => new(name, MilvusDataType.Geometry, description: description, nullable: nullable);

    /// <summary>
    /// Create a field schema for a timezone-aware timestamp field. Available since Milvus v2.6.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="description">An optional description for the field.</param>
    /// <param name="nullable">Whether the field accepts null values.</param>
    /// <remarks>
    /// Values are exchanged as ISO 8601 strings, e.g. <c>2025-01-01T00:00:00Z</c>. The output
    /// timezone can be controlled by setting a <c>timezone</c> property (an IANA name such as
    /// <c>America/New_York</c>) on the database or collection.
    /// </remarks>
    public static FieldSchema CreateTimestamptz(string name, string description = "", bool nullable = false)
        => new(name, MilvusDataType.Timestamptz, description: description, nullable: nullable);

    /// <summary>
    /// Create a field schema for a <c>text</c> field. Available since Milvus v2.6. Intended for longer
    /// free-form content than <c>varchar</c>; shares the same wire representation, but cannot be a
    /// primary key, a partition key, or an array element type, and does not support a default value.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="maxLength">
    /// The maximum length of the field. Milvus's own schema validation does not enforce this at
    /// collection-creation time, and a request omitting it is accepted -- but doing so is far more
    /// dangerous than a mere validation gap. Root-caused against a live Milvus 2.6.4 container (via the
    /// server's own logs, not just symptoms): its streaming-node flusher unrecoverably panics --
    /// crashing the <em>entire server process</em>, not just the one request -- the next time it
    /// recovers/rescans WAL channels and finds a collection with a <see cref="MilvusDataType.Text" />
    /// field lacking this value:
    /// <code>
    /// panic: new a empty data sync service should never be failed, the max_length was not specified, field type is Text
    ///   .../flushcommon/pipeline.NewEmptyStreamingNodeDataSyncService(...)
    ///   .../flusherimpl.(*flusherComponents).WhenCreateCollection(...)
    ///   created by .../flusherimpl.RecoverWALFlusher
    /// </code>
    /// Because that recovery pass can run well after the collection was created (even after it was
    /// dropped again, if the pass catches it mid-window), the crash can surface much later and appear
    /// to hit an unrelated, unlucky operation. <c>maxLength</c> is required here specifically to make
    /// this unreachable through the public API -- there is no supported way to opt out of it. The
    /// general <see cref="Create(string, MilvusDataType, bool, bool, bool, string, bool, object?)" />
    /// overload still accepts a <see cref="MilvusDataType.Text" /> field with no <see cref="MaxLength" />
    /// set (it has no maxLength parameter to require one through), so <see cref="ToGrpc" /> itself rejects
    /// that shape for any field, regardless of which factory built it.
    /// </param>
    /// <param name="description">An optional description for the field.</param>
    /// <param name="nullable">Whether the field can contain null values.</param>
    /// <param name="enableAnalyzer">
    /// Whether to enable the analyzer for this field. Required for BM25 full-text search input fields
    /// and for <paramref name="enableMatch" />-based <c>TEXT_MATCH</c> filtering.
    /// </param>
    /// <param name="analyzerParams">
    /// Optional analyzer parameters. For example: <c>new Dictionary&lt;string, object&gt; { ["type"] = "english" }</c>.
    /// </param>
    /// <param name="enableMatch">
    /// Whether to build an inverted index enabling <c>TEXT_MATCH</c> filter expressions against this
    /// field. Requires <paramref name="enableAnalyzer" /> to also be true.
    /// <para>
    /// As of Milvus 2.6.4, <c>TEXT_MATCH</c> (and every other filter expression) against a
    /// <see cref="MilvusDataType.Text" /> field is rejected server-side with "filter on text field (...)
    /// is not supported yet", regardless of this setting -- filtering by content currently requires a
    /// <see cref="MilvusDataType.VarChar" /> field instead. The field can still be created, inserted
    /// into, and read back (including via <c>OutputFields</c>); only expression-based filtering on it is
    /// blocked. Revisit once a newer Milvus version lifts this restriction.
    /// </para>
    /// </param>
    public static FieldSchema CreateText(
        string name,
        int maxLength,
        string description = "",
        bool nullable = false,
        bool enableAnalyzer = false,
        IReadOnlyDictionary<string, object>? analyzerParams = null,
        bool enableMatch = false)
        => new(name, MilvusDataType.Text, description: description, nullable: nullable)
        {
            MaxLength = maxLength,
            EnableAnalyzer = enableAnalyzer,
            AnalyzerParams = analyzerParams,
            EnableMatch = enableMatch
        };

    /// <summary>
    /// Create a field schema for a sparse float vector field. Available since Milvus v2.4.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="description">An optional description for the field.</param>
    /// <remarks>
    /// Sparse float vectors do not have a fixed dimension. The dimension is determined by the
    /// maximum index of the non-zero elements across all vectors.
    /// </remarks>
    public static FieldSchema CreateSparseFloatVector(string name, string description = "")
        => new(name, MilvusDataType.SparseFloatVector, description: description);

    /// <summary>
    /// Create a field schema for a <c>array</c> of <c>TData</c> field.
    /// </summary>
    /// <typeparam name="TData">Determines the element data type of array stored in the field based.</typeparam>
    /// <param name="name">The field name.</param>
    /// <param name="maxCapacity">Maximum number of elements that an array field can contain.</param>
    /// <param name="description">An optional description for the field.</param>
    /// <param name="nullable">Whether the field can contain null values. Available since Milvus v2.5.</param>
    public static FieldSchema CreateArray<TData>(
        string name,
        int maxCapacity,
        string description = "",
        bool nullable = false)
        => new(name, MilvusDataType.Array, description: description, nullable: nullable)
        {
            ElementDataType = FieldData.EnsureDataType<TData>(),
            MaxCapacity = maxCapacity,
        };

    /// <summary>
    /// Create a field schema for a <c>array</c> of <c>varchar</c> field.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="maxCapacity">Maximum number of elements that an array field can contain.</param>
    /// <param name="maxLength">Maximum length of strings for each <c>varchar</c> element in an array field.</param>
    /// <param name="description">An optional description for the field.</param>
    /// <param name="nullable">Whether the field can contain null values. Available since Milvus v2.5.</param>
    public static FieldSchema CreateVarcharArray(
        string name,
        int maxCapacity,
        int maxLength,
        string description = "",
        bool nullable = false)
        => new(name, MilvusDataType.Array, description: description, nullable: nullable)
        {
            ElementDataType = MilvusDataType.VarChar,
            MaxCapacity = maxCapacity,
            MaxLength = maxLength,
        };

    // Construct used when the user constructs a schema to be provided to CreateSchema
    private FieldSchema(
        string name,
        MilvusDataType dataType,
        bool isPrimaryKey = false,
        bool autoId = false,
        bool isPartitionKey = false,
        string description = "",
        bool nullable = false,
        object? defaultValue = null)
    {
        Name = name;
        DataType = dataType;
        Nullable = nullable;
        State = FieldState.Unknown;
        IsPrimaryKey = isPrimaryKey;
        AutoId = autoId;
        IsPartitionKey = isPartitionKey;
        DefaultValue = defaultValue;
        Description = description;
    }

    // Constructor used when retrieving a schema via DescribeSchema
    internal FieldSchema(
        long id,
        string name,
        MilvusDataType dataType,
        MilvusDataType elementType,
        FieldState state,
        bool isPrimaryKey,
        bool autoId,
        bool isPartitionKey,
        bool isDynamic,
        string description,
        bool nullable,
        object? defaultValue)
    {
        FieldId = id;
        Name = name;
        DataType = dataType;
        ElementDataType = elementType;
        State = state;
        IsPrimaryKey = isPrimaryKey;
        AutoId = autoId;
        IsPartitionKey = isPartitionKey;
        IsDynamic = isDynamic;
        Description = description;
        Nullable = nullable;
        DefaultValue = defaultValue;
    }

    /// <summary>
    /// The field name.
    /// </summary>
    public string Name { get; }

    /// <summary>
    /// The data type stored in the field.
    /// </summary>
    public MilvusDataType DataType { get; }

    /// <summary>
    /// The element data type for array stored in the field.
    /// </summary>
    public MilvusDataType ElementDataType { get; set; }

    /// <summary>
    /// Whether the field is a primary key.
    /// </summary>
    public bool IsPrimaryKey { get; }

    /// <summary>
    /// Whether the field's values are automatically generated by Milvus.
    /// </summary>
    public bool AutoId { get; }

    /// <summary>
    /// Whether the field functions as the partition key for the collection. Available since Milvus v2.2.9.
    /// </summary>
    /// <remarks>
    /// <para>A partition key field's values are hashed and distributed to different logical partitions.</para>
    /// <para>
    /// Only fields of type <see cref="MilvusDataType.Int64" /> and <see cref="MilvusDataType.VarChar" /> type can be
    /// partition keys. The primary key field cannot be a partition key.
    /// </para>
    /// </remarks>
    public bool IsPartitionKey { get; }

    /// <summary>
    /// An optional description for the field.
    /// </summary>
    public string Description { get; }

    /// <summary>
    /// Whether the field can contain null values. Available since Milvus v2.5.
    /// </summary>
    /// <remarks>
    /// <para>
    /// For fields marked as nullable, users can omit the field when inserting data or set it directly to a null value.
    /// The system will treat it as null without throwing an error.
    /// </para>
    /// <para>
    /// Nullable fields cannot be used as partition keys. Primary key fields cannot be nullable.
    /// </para>
    /// </remarks>
    public bool Nullable { get; }

    /// <summary>
    /// The default value for the field. Available since Milvus v2.5.
    /// </summary>
    /// <remarks>
    /// <para>
    /// When a field has a default value, the system will automatically apply this value if no data is specified for
    /// the field during insertion.
    /// </para>
    /// <para>
    /// Default values are only supported for scalar fields (bool, int8, int16, int32, int64, float, double, varchar).
    /// Array and JSON fields do not support default values.
    /// </para>
    /// </remarks>
    public object? DefaultValue { get; set; }

    /// <summary>
    /// Whether this field was created dynamically. Available since Milvus v2.2.9.
    /// </summary>
    /// <remarks>
    /// <see href="https://milvus.io/docs/dynamic_schema.md" />
    /// </remarks>
    public bool IsDynamic { get; }

    /// <summary>
    /// The maximum string length. Mandatory for <see cref="MilvusDataType.VarChar" /> fields, and must be greater than
    /// zero.
    /// </summary>
    public int? MaxLength { get; set; }

    /// <summary>
    /// Maximum number of elements that an array field can contain. Mandatory for <see cref="MilvusDataType.Array" /> fields, and must be in a range [1, 4096]
    /// </summary>
    public int? MaxCapacity { get; set; }

    /// <summary>
    /// The dimension of the vector. Mandatory for <see cref="MilvusDataType.FloatVector" />,
    /// <see cref="MilvusDataType.BinaryVector" />, and <see cref="MilvusDataType.Float16Vector" /> fields,
    /// and must be greater than zero. Not applicable for <see cref="MilvusDataType.SparseFloatVector" /> fields.
    /// </summary>
    public int? Dimension { get; set; }

    /// <summary>
    /// Whether to enable the analyzer for this field. Required for BM25 full-text search input fields
    /// and for <see cref="EnableMatch" />-based <c>TEXT_MATCH</c> filtering.
    /// </summary>
    /// <remarks>
    /// When enabled, the field can be used as an input to a BM25 function for full-text search.
    /// This property is only applicable for <see cref="MilvusDataType.VarChar" /> and
    /// <see cref="MilvusDataType.Text" /> fields.
    /// </remarks>
    public bool EnableAnalyzer { get; set; }

    /// <summary>
    /// Optional analyzer parameters. For example: <c>new Dictionary&lt;string, object&gt; { ["type"] = "english" }</c>.
    /// </summary>
    /// <remarks>
    /// This property is only applicable when <see cref="EnableAnalyzer" /> is set to true.
    /// </remarks>
    public IReadOnlyDictionary<string, object>? AnalyzerParams { get; set; }

    /// <summary>
    /// Whether to build an inverted index enabling <c>TEXT_MATCH</c> filter expressions against this
    /// field. Available since Milvus v2.5.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Requires <see cref="EnableAnalyzer" /> to also be set to <see langword="true" /> -- Milvus rejects a
    /// <c>TEXT_MATCH</c> filter against a field where match is not enabled with an error naming the field,
    /// e.g. <c>field "x" does not enable match</c> (verified against Milvus 2.6.4).
    /// </para>
    /// <para>
    /// This property is only applicable for <see cref="MilvusDataType.VarChar" /> and
    /// <see cref="MilvusDataType.Text" /> fields.
    /// </para>
    /// </remarks>
    public bool EnableMatch { get; set; }

    /// <summary>
    /// Whether this field is the output of a function and should not be provided during insertion.
    /// </summary>
    public bool IsFunctionOutput { get; internal set; }

    /// <summary>
    /// The state of the field.
    /// </summary>
    public FieldState State { get; private set; }

    /// <summary>
    /// The internal Milvus ID assigned to this ID.
    /// </summary>
    public long FieldId { get; }

    private string DebuggerDisplay => $"{Name} ({DataType})";

    /// <summary>
    /// Converts this field schema to its wire representation. Shared by <c>CreateCollection</c>, which sends a
    /// whole schema, and <c>AddCollectionField</c>, which sends one field's schema on its own.
    /// </summary>
    internal Grpc.FieldSchema ToGrpc()
    {
        if (DataType == MilvusDataType.Text && MaxLength is null)
        {
            throw new ArgumentException(
                $"Field '{Name}' is a {nameof(MilvusDataType.Text)} field with no {nameof(MaxLength)}. Milvus's own " +
                "schema validation does not catch this at collection-creation time, but a live Milvus 2.6.4 container " +
                "crashes its entire server process on a delayed WAL-recovery pass when it finds one -- see " +
                $"{nameof(CreateText)}'s documentation for the full panic trace. Set {nameof(MaxLength)}, e.g. via " +
                $"{nameof(CreateText)}, instead of the general {nameof(Create)} overload.");
        }

        if (EnableMatch && !EnableAnalyzer)
        {
            throw new ArgumentException(
                $"Field '{Name}' has {nameof(EnableMatch)} set without {nameof(EnableAnalyzer)}. " +
                $"{nameof(EnableMatch)} requires {nameof(EnableAnalyzer)} to also be true -- see " +
                $"{nameof(EnableMatch)}'s documentation.");
        }

        Grpc.FieldSchema grpcField = new()
        {
            Name = Name,
            DataType = (Grpc.DataType)(int)DataType,
            ElementType = (Grpc.DataType)(int)ElementDataType,
            IsPrimaryKey = IsPrimaryKey,
            IsPartitionKey = IsPartitionKey,
            AutoID = AutoId,
            Nullable = Nullable,
            Description = Description
        };

        if (MaxLength is not null)
        {
            grpcField.TypeParams.Add(new Grpc.KeyValuePair
            {
                Key = Constants.VarcharMaxLength,
                Value = MaxLength.Value.ToString(CultureInfo.InvariantCulture)
            });
        }

        if (Dimension is not null)
        {
            grpcField.TypeParams.Add(new Grpc.KeyValuePair
            {
                Key = Constants.VectorDim,
                Value = Dimension.Value.ToString(CultureInfo.InvariantCulture)
            });
        }

        if (MaxCapacity is not null)
        {
            grpcField.TypeParams.Add(new Grpc.KeyValuePair
            {
                Key = Constants.MaxCapacity,
                Value = MaxCapacity.Value.ToString(CultureInfo.InvariantCulture)
            });
        }

        if (DefaultValue is not null)
        {
            grpcField.DefaultValue = ConvertToValueField(DefaultValue, DataType);
        }

        if (EnableAnalyzer)
        {
            grpcField.TypeParams.Add(new Grpc.KeyValuePair
            {
                Key = Constants.EnableAnalyzer,
                Value = "true"
            });
        }

        if (AnalyzerParams is not null)
        {
            grpcField.TypeParams.Add(new Grpc.KeyValuePair
            {
                Key = Constants.AnalyzerParams,
                Value = JsonSerializer.Serialize(AnalyzerParams)
            });
        }

        if (EnableMatch)
        {
            grpcField.TypeParams.Add(new Grpc.KeyValuePair
            {
                Key = Constants.EnableMatch,
                Value = "true"
            });
        }

        return grpcField;
    }

    private static Grpc.ValueField ConvertToValueField(object value, MilvusDataType dataType)
    {
        Grpc.ValueField valueField = new();

        switch (dataType)
        {
            case MilvusDataType.Bool:
                valueField.BoolData = (bool)value;
                break;
            case MilvusDataType.Int8:
            case MilvusDataType.Int16:
            case MilvusDataType.Int32:
                valueField.IntData = Convert.ToInt32(value, CultureInfo.InvariantCulture);
                break;
            case MilvusDataType.Int64:
                valueField.LongData = Convert.ToInt64(value, CultureInfo.InvariantCulture);
                break;
            case MilvusDataType.Float:
                valueField.FloatData = Convert.ToSingle(value, CultureInfo.InvariantCulture);
                break;
            case MilvusDataType.Double:
                valueField.DoubleData = Convert.ToDouble(value, CultureInfo.InvariantCulture);
                break;
            case MilvusDataType.String:
            case MilvusDataType.VarChar:
                valueField.StringData = (string)value;
                break;
            default:
                throw new ArgumentException(
                    $"Default values are not supported for {dataType} fields. Only scalar fields support default values.",
                    nameof(value));
        }

        return valueField;
    }
}
